# Configuration for gh-changelog
# Labels added here will be omitted from the changelog
excluded_labels:
  - maintenance
  - dependencies
  - wontfix
  - duplicate
  - invalid

# This is the filename of the generated changelog
file_name: CHANGELOG.md

# This is where labels are mapped to the sections in a changelog entry
# The possible sections are restricted to: Added, Changed, Deprecated,
# Removed, Fixed, Security.
sections:
  added:
    - enhancement
    - feature
    - new
  changed:
    - backwards-incompatible
    - breaking-change
    - change
  deprecated:
    - deprecation
  removed:
    - removal
  fixed:
    - bug
    - bugfix
    - fix
  security:
    - security
    - vulnerability

# When set to true, unlabelled entries will not be included in the changelog.
# By default they will be grouped in a section named "Other".
skip_entries_without_label: false

# Adds an unreleased section to the changelog. This will contain any qualifying entries
# that have been added since the last tag.
# Note: The unreleased section is not created when the --next-version flag is used.
show_unreleased: true

# If set to false, the tool will not check remotely for updates
check_for_updates: true

# Determines the logging mode. The default is spinner. The other option is console.
logger: console
